stages:
    - test
    - build
    - deploy

variables: 
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    SONAR_HOST_URL: "http://localsonarqube:9000/"
    SONAR_TOKEN: "squ_35c667f3567119d5702ffa5fb92ca6eaac5889a6"
    SONAR_USER: "gitlab-runner"
    SONAR_PASSWORD: "Password@123"
    DEPLOY_STAGING_SSH_HOST: "ec2-user@172.16.1.121"
default:
    cache:
        paths:
            - .m2/repository/
            - target/
    image: maven:3-openjdk-11

test:
    stage: test
    script:
      - mvn verify sonar:sonar
    rules:
      - if: $CI_COMMIT_BRANCH == "staging"
        allow_failure: true
    artifacts:
        untracked: false
        name: test_and_coverage_report
        reports:
          junit: [ api/target/surefire-reports/*.xml ]
        expire_in: "1 week"

build_java:
    stage: build
    script:
      - mvn package -Pwar -DskipTests=true 
    artifacts:
        paths:
          - batch/target/govio-batch.war
          - api/target/govio.war
          - src/main/resources/*.sql
    only:
      - main
      - staging

build_angular:
    stage: build
    image: node:14.18.2-alpine3.15
    script:
      - cd webapp
      - npm install
      - npm run production-govio
      - tar czf govio-app.tgz dist/*  
    artifacts:
        paths:
          - webapp/govio-app.tgz
    only:
      - main
      - staging

deploy_staging:
  stage: deploy
  image: kroniak/ssh-client
  script:
    - cp -r /tmp/ssh/ ~/.ssh
    - scp -r webapp/govio-app.tgz $DEPLOY_STAGING_SSH_HOST:/tmp/
    - scp -r batch/target/govio-batch.war $DEPLOY_STAGING_SSH_HOST:/tmp/
    - scp -r api/target/govio.war $DEPLOY_STAGING_SSH_HOST:/tmp/
    - ssh $DEPLOY_STAGING_SSH_HOST 'sudo tar xvf /tmp/govio-app.tgz'
    - ssh $DEPLOY_STAGING_SSH_HOST 'sudo cp -r dist/govio-app/* /usr/share/nginx/html/govio-app/'
    - ssh $DEPLOY_STAGING_SSH_HOST 'sudo cp -r /tmp/govio-batch.war /tmp/govio.war /opt/wildfly/govhub/deployments/'  
    - ssh $DEPLOY_STAGING_SSH_HOST 'sudo systemctl restart wildfly@govhub'
    - ssh $DEPLOY_STAGING_SSH_HOST 'sudo rm -rf /tmp/govio-app.tgz dist /tmp/govio-batch.war /tmp/govio.war'
  only:
    - staging
