openapi: 3.0.3

info:
  title: GovIO API - OpenAPI 3.0
  x-summary: GovIO Communications
  description: This API Describes manages the govhub messages. 
  x-api-id: govio-backoffice
  termsOfService: TODO
  version: 1.0.1
  contact:
    name: TODO
    email: TODO@TODO.it

  license:
    name: Apache 2.0 ( TODO )
    url: http://www.apache.org/licenses/LICENSE-2.0.html 
  
tags:
  - name: trace
    description: File Trace Operations
    
servers:
  - url: http://localhost:10001
    description: Sample Deployment URL (Not Actual)
    
security:
   - header-principal: []

paths:  
    /files:
       post:
         tags:
           - trace
         summary: Upload a new csv trace.
         description: Allows to upload a csv trace for a GovIO service.
         operationId: uploadCsvTrace
         parameters:
            - $ref: "#/components/parameters/service_id_query"
            - $ref: "#/components/parameters/organization_id_query"
         requestBody:
           content:
             multipart/form-data:
               schema:
                 type: object
                 properties: # Request parts
                   name:
                     type: string
                   file:
                     type: string
                     format: binary
               encoding: # The same level as schema
                 file: # Property name (see above)
                   contentType: text/csv
         responses:
           '200':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovIOFile'          
           '400':
             $ref: "govhub-api-commons.yaml#/components/responses/400BadRequest"
           '401':
             $ref: "govhub-api-commons.yaml#/components/responses/401Unauthorized"
           '403':
             $ref: "govhub-api-commons.yaml#/components/responses/403Forbidden"
           '404':
             $ref: "govhub-api-commons.yaml#/components/responses/404NotFound"
           '429':
             $ref: "govhub-api-commons.yaml#/components/responses/429TooManyRequests"
           '503':
             $ref: "govhub-api-commons.yaml#/components/responses/503ServiceUnavailable"
           default:
             $ref: "govhub-api-commons.yaml#/components/responses/ResponseDefault"


components:

   # SECURITY    ---------------
   securitySchemes:
      header-principal:
         type: apiKey
         in: header
         name: GovHub-Consumer-Principal

   parameters:
   
      organization_id_query:
         name: organization_id
         in: query
         required: true
         schema:
           $ref: "govhub-api-commons.yaml#/components/schemas/OrganizationId"
   
      service_id_query:
         name: service_id
         in: query
         required: true
         schema:
           $ref: "govhub-api-commons.yaml#/components/schemas/ServiceId"   

   schemas:
   
      GovIOFile:
         type: object
         additionalProperties: false
         properties:
           detail:
             type: string
   