create sequence seq_govio_file_messages start 1 increment 1;
create sequence seq_govio_files start 1 increment 1;
create sequence seq_govio_messages start 1 increment 1;
create sequence seq_govio_placeholders start 1 increment 1;
create sequence seq_govio_service_instances start 1 increment 1;
create sequence seq_govio_templates start 1 increment 1;
create table govio_files (id int8 not null, acquired_messages int8, creation_date timestamp not null, error_messages int8, location varchar(255) not null, name varchar(255) not null, status varchar(255) not null, id_govio_service_instance int8 not null, primary key (id));
create table govio_files_messages (id int8 not null, error varchar(255), line_number int8, line_record varchar(255), id_govio_file int8 not null, id_govio_message int8, primary key (id));
create table govio_messages (id int8 not null, amount int8, appio_message_id varchar(255), creation_date timestamp not null, due_date timestamp, email varchar(255), expedition_date timestamp, invalid_after_due_date boolean, last_update_status timestamp, markdown varchar(255) not null, notice_number varchar(255), payee varchar(255), scheduled_expedition_date timestamp not null, status varchar(255) not null, subject varchar(255) not null, taxcode varchar(255) not null, id_govio_service_instance int8 not null, primary key (id));
create table govio_placeholders (id int8 not null, description varchar(255), example varchar(255) not null, name varchar(255) not null, pattern varchar(255), type varchar(255) not null, primary key (id));
create table govio_service_instances (id int8 not null, apikey varchar(255) not null, id_govio_service int8 not null, id_govio_template int8 not null, primary key (id));
create table govio_template_placeholders (id_govio_placeholder int8 not null, id_govio_template int8 not null, index int4 not null, mandatory boolean not null, primary key (id_govio_placeholder, id_govio_template));
create table govio_templates (id int8 not null, description varchar(255), has_due_date boolean not null, has_payment boolean not null, message_body varchar(255) not null, name varchar(255), subject varchar(255) not null, primary key (id));
alter table govio_files add constraint FK9te7wpln11mq48levwtliu8u9 foreign key (id_govio_service_instance) references govio_service_instances;
alter table govio_files_messages add constraint FKepx8m4vtto26112hum2hhc622 foreign key (id_govio_file) references govio_files;
alter table govio_files_messages add constraint FKcx8eekk6vqn9ty4u9rtx46xfi foreign key (id_govio_message) references govio_messages;
alter table govio_messages add constraint FKla48cb1g0xu9h858f6wjncm37 foreign key (id_govio_service_instance) references govio_service_instances;
alter table govio_service_instances add constraint FKhjvivd89ic6jgic207vymsdby foreign key (id_govio_template) references govio_templates;
alter table govio_template_placeholders add constraint FKehkew4fssbtp7d067gad1gc51 foreign key (id_govio_placeholder) references govio_placeholders;
alter table govio_template_placeholders add constraint FKlvxcogacjjhnvd9f5xxi8md6n foreign key (id_govio_template) references govio_templates;
